# Numpy

In [1]:
import numpy as np

In [2]:
np.full((3,3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [5]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [6]:
# 10 to 15
array1 = np.arange(10,20)
# 10 to 20. 2 by 2
array2 = np.arange(10,20,2)
# 5 steps from 0 to 1...
array3 = np.linspace(0, 1, 5)
# Generate an array from 1 to 10, in log10 space in 10 steps...
array4 = np.logspace(0, 1, 10, base=10.0)

In [7]:
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
array2

array([10, 12, 14, 16, 18])

In [9]:
array3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
array4

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [11]:
diagonal = np.eye(3)
diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
custom_diagonal = np.diag([1,2,3])
custom_diagonal


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Slice and dice

### Stacking

In [13]:
array_stack = np.array([1,2,3])

In [14]:
array_stack

array([1, 2, 3])

In [19]:
np.tile(array_stack, [3,2])

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Random numbers

In [20]:
np.random.random()

0.18678749557026275

In [21]:
np.random.random(2)

array([0.35725608, 0.85339947])

In [24]:
np.random.random([3,2])

array([[0.80038398, 0.56725183],
       [0.76462484, 0.44012246],
       [0.5956858 , 0.1327121 ]])

### Broadcasting