In [1]:
import numpy as np
import tensorflow as tf

#### Check Tensorflow version

In [2]:
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 1.11.0


In [3]:
#### 

In [4]:
tf.zeros(3)

<tf.Tensor 'zeros:0' shape=(3,) dtype=float32>

In [5]:
all_zeros = tf.ones(4)

In [6]:
tf.InteractiveSession()
all_zeros.eval()

array([1., 1., 1., 1.], dtype=float32)

In [7]:
all_threes = tf.fill((3, 3), value=3.)
all_threes.eval()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [8]:
normal_distribution = tf.random_normal((3, 5), mean=0, stddev=1)
normal_distribution.eval()

array([[ 0.7289754 , -0.33683524,  1.3414998 ,  0.414079  ,  0.5140987 ],
       [ 0.6543295 ,  0.5457566 ,  0.15177472, -0.81899786, -0.5091408 ],
       [-1.7153441 , -0.6265775 , -0.25846046, -0.3169766 ,  0.60636026]],
      dtype=float32)

In [9]:
x = tf.constant([3])
y = tf.constant([4])
z = tf.add(x,y)
session = tf.Session()
result = session.run(z)
print(result)


[7]


In [10]:
x = tf.constant([1,2,3,4])
y = tf.constant([5,6,7,8])

result = tf.multiply(x,y)
session = tf.Session()
print(session.run(result))
session.close()

[ 5 12 21 32]


In [11]:
x = tf.constant([1,2,3,4])
y = tf.constant([5,6,7,8])
z = tf.multiply(x, y)

print(z.eval())

[ 5 12 21 32]


In [12]:
import torch
x = torch.Tensor([3])
y = torch.Tensor([4])
z = x+y
print(z)

tensor([7.])


In [13]:
def rmse(y, y_hat):
    y_actual=np.array(y)
    y_pred=np.array(y_hat)
    error=(y_actual-y_pred)**2
    error_mean=round(np.mean(error))
    error_sqrt=sqrt(error_mean)
    return error_sqrt

In [14]:
from sklearn import metrics

def rmse(y, y_hat):
    return np.sqrt(metrics.mean_squared_error(y, y_hat))

In [15]:
def rmse(y, y_hat):
    return tf.sqrt(tf.reduce_mean(tf.square((y - y_hat))))

In [16]:
def rmse(y, y_hat):
    return tf.sqrt(tf.reduce_mean(tf.square((y - y_hat))))